cursor #dae6d9
cursor_text_color #becabd

foreground            #dae6d9
background            #0c160e
selection_foreground  #0c3729
selection_background  #a4d0bc
url_color             #00e47c

color0   #0c160e
color1   #ff4d00
color2   #00e408
color3   #ffe700
color4   #00d875
color5   #006939
color6   #00e47c
color7   #d2efe2
color8   #7d948a
color9   #ff7a3f
color10  #4cff52
color11  #ffee4c
color12  #25fa99
color13  #4cffad
color14  #8cffca
color15  #f2fff9
