# KITTY — GLASS / TAHOE (strong effect)

# FONT
font_family JetBrainsMono Nerd Font
font_size 15.0
bold_font auto
italic_font auto
bold_italic_font auto

# WINDOW / GLASS
background_opacity 0.72
window_padding_width 16
hide_window_decorations yes
confirm_os_window_close 0

# Borders/tabs (clean)
draw_minimal_borders yes
window_border_width 1pt
active_border_color #89b4fa
inactive_border_color #313244

tab_bar_style powerline
tab_powerline_style slanted
active_tab_background #89b4fa
active_tab_foreground #11111b
inactive_tab_background #1e1e2e
inactive_tab_foreground #a6adc8

# COLORS
foreground #dce6ff
background #0b1020
cursor #cdd6f4
cursor_text_color #0b1020
selection_foreground #0b1020
selection_background #9cc5ff

color0  #1e1e2e
color1  #f38ba8
color2  #a6e3a1
color3  #f9e2af
color4  #89b4fa
color5  #cba6f7
color6  #94e2d5
color7  #bac2de
color8  #585b70
color9  #f38ba8
color10 #a6e3a1
color11 #f9e2af
color12 #89b4fa
color13 #cba6f7
color14 #94e2d5
color15 #e6e9ef

# QoL
enable_audio_bell no
copy_on_select yes
shell_integration enabled

map ctrl+shift+t new_tab
map ctrl+shift+w close_window
map ctrl+shift+enter new_window
