color0 #1a1111
color1 #ffb4ab
color2 #f5be50
color3 #f8b6b3
color4 #ffb3b0
color5 #f5be50
color6 #f8b6b3
color7 #f1dedd
color8 #a48b89
color9 #ffb4ab
color10 #f5be50
color11 #f8b6b3
color12 #ffb3b0
color13 #f5be50
color14 #f8b6b3
color15 #f1dedd

cursor                #f1dedd
cursor_text_color     #1a1111
background            #1a1111
foreground            #f1dedd
selection_foreground  #dcc0be
selection_background  #564241
url_color             #ffb3b0