background {
  monitor =
  color = rgba(25,25,35,1.0)
}
input-field {
  monitor =
  size = 320, 52
  outline_thickness = 2
  outer_color = rgba(137, 180, 250, 1.0)
  inner_color = rgba(30, 30, 46, 0.9)
  font_color = rgba(205, 214, 244, 1.0)
  rounding = 10
  position = 0, -80
  halign = center
  valign = center
}
