add_newline = true

format = "$os$username$hostname$directory$git_branch$git_status$line_break$character"

[os]
disabled = false
format = "[$symbol]($style) "
style = "bold #89b4fa"

[os.symbols]
Arch = "󰣇"
Ubuntu = "󰕈"
Windows = "󰍲"
Macos = "󰀵"
Linux = "󰌽"
Unknown = "❓"

[username]
show_always = true
style_user = "bold #cba6f7"
style_root = "bold red"
format = "[😼 $user]($style) "

[hostname]
ssh_only = false
style = "bold #94e2d5"
format = "[on 󰒋 $hostname]($style) "

[directory]
style = "bold #b4befe"
truncation_length = 4
truncate_to_repo = true
format = "[in   $path]($style) "

[git_branch]
symbol = " "
style = "bold #a6e3a1"

[git_status]
style = "#f9e2af"

[character]
success_symbol = "[❯](bold #89b4fa)"
error_symbol = "[❯](bold #f38ba8)"
