monitor=,preferred,auto,1
$terminal = kitty
$menu = wofi --show drun
$browser = firefox
exec-once = waybar
exec-once = swaync
input {
  kb_layout = br
  follow_mouse = 1
}
general {
  gaps_in = 5
  gaps_out = 10
  border_size = 2
  col.active_border = rgba(89b4faff)
  col.inactive_border = rgba(5b6078ff)
  layout = dwindle
}
bind = SUPER, Return, exec, $terminal
bind = SUPER, Q, killactive,
bind = SUPER, M, exit,
bind = SUPER, D, exec, $menu
bind = SUPER, B, exec, $browser
bind = SUPER, F, fullscreen,
bind = SUPER, V, togglefloating,
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2
bind = SUPER SHIFT, 3, movetoworkspace, 3
bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow
