# Hyprland base (minimal)
monitor=,preferred,auto,1

$terminal = kitty
$fileManager = thunar

bind = SUPER, Return, exec, $terminal
bind = SUPER, E, exec, $fileManager
bind = SUPER, Q, killactive,
bind = SUPER, M, exit,

bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3

bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow
