# Hyprland modular
source = ~/.config/hypr/conf.d/00-monitors.conf
source = ~/.config/hypr/conf.d/10-env.conf
source = ~/.config/hypr/conf.d/20-autostart.conf
source = ~/.config/hypr/conf.d/30-input.conf
source = ~/.config/hypr/conf.d/40-looknfeel.conf
source = ~/.config/hypr/conf.d/50-layouts.conf
source = ~/.config/hypr/conf.d/60-keybinds.conf
source = ~/.config/hypr/conf.d/70-rules.conf
source = ~/.config/hypr/conf.d/90-misc.conf
