#!/usr/bin/env bash
if command -v flatpak &>/dev/null && flatpak info app.zen_browser.zen &>/dev/null; then
    flatpak run app.zen_browser.zen --class=browser
elif command -v brave &>/dev/null; then
    brave --class=browser
elif command -v firefox &>/dev/null; then
    firefox --class=browser
else
    echo "Nenhum navegador encontrado." >&2
fi
