#!/usr/bin/env bash

if command -v thunar &>/dev/null; then
    thunar --class=archive
elif command -v nautilus &>/dev/null; then
    nautilus --class=archive
elif command -v dolphin &>/dev/null; then
    dolphin --class=archive
elif command -v pcmanfm &>/dev/null; then
    pcmanfm --class=archive
else
    echo "Nenhum gerenciador de arquivos encontrado." >&2
fi
