cursor #eae0e7
cursor_text_color #cfc3cd

foreground            #eae0e7
background            #161217
selection_foreground  #3a2b3d
selection_background  #d5c0d7
url_color             #e6b6f1

color0   #161217
color1   #ff7286
color2   #78f198
color3   #ffdd72
color4   #d8a1e4
color5   #663d6f
color6   #e6b6f1
color7   #faedfd
color8   #9a909c
color9   #ff9fac
color10  #a5ffbd
color11  #ffe9a5
color12  #f5c9ff
color13  #f6d3ff
color14  #f9e2ff
color15  #fdf8ff
