#################
### AUTOSTART
#################

# === Importar variáveis para sessão ===
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_DATA_DIRS PATH
exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_DATA_DIRS PATH QT_QPA_PLATFORM QT_QPA_PLATFORMTHEME

# === Applets e Serviços ===
exec-once = nm-applet &
exec-once = fcitx5



# === Polkit (autenticação) ===
#exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Core components (authentication, lock screen, notification daemon)
exec-once = hypridle

# === Scripts e Utilitários ===
#exec-once = ~/.config/hypr/scripts/dircreate.sh
exec-once = wl-paste --watch cliphist store
exec-once=wl-paste --type text --watch cliphist store
exec-once=wl-paste --type image --watch cliphist store

# === Shell do Sistema DankMaterialShell===
#exec-once = dms run

# === Shell do Sistema Caelestia-shell===
#exec-once = dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP && sleep 2 && qs -c caelestia

# === Shell do Sistema Noctalia-shell===
exec-once = qs -c noctalia-shell

# === Regras de Monitor ===
exec-once = hyprctl dispatch workspace 1 DP-1
exec-once = hyprctl dispatch workspace 2 HDMI-A-2

# Atualizar ícones ao iniciar
exec-once = ~/.config/hypr/scripts/update-icons.sh

#controle de ventoinha da rx580
exec-once = corectrl --minimize-systray
exec-once = ~/.config/hypr/scripts/gpu-fan-control.sh &



exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
