#exec-once = mpvpaper -f -o "no-audio --loop-file --hwdec=auto-safe --vo=gpu --gpu-context=wayland --panscan=1.0 --video-unscaled=no --scale=bilinear --vd-lavc-threads=1" "DP-1" "/home/michael/livewallpapers/cosmic-sakura-gaze-moewalls-com.mp4"
#exec-once = mpvpaper -f -o "no-audio --loop-file --hwdec=auto-safe --vo=gpu --gpu-context=wayland --panscan=1.0 --video-unscaled=no --scale=bilinear --vd-lavc-threads=1" "HDMI-A-2" "/home/michael/livewallpapers/cosmic-sakura-gaze-moewalls-com.mp4"


##!swww##
#exec-once = swww-daemon &
#exec-once = swww img -o HDMI-A-2 /home/michael/livewallpapers/2.gif
#exec-once = swww img -o DP-1 /home/michael/livewallpapers/3.gif
