# QT
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_QPA_PLATFORMTHEME,qt5ct
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_AUTO_SCREEN_SCALE_FACTOR,1

env = TERMINAL,kitty
# === Environment Variables ===
env = XDG_DATA_DIRS,$XDG_DATA_DIRS:/var/lib/flatpak/exports/share:~/.local/share/flatpak/exports/share
env = PATH,$PATH:~/.local/bin

# === Extras úteis (opcional) ===
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
env = GDK_BACKEND,wayland,x11,*  # GTK apps usarem Wayland primeiro
env = SDL_VIDEODRIVER,wayland  # SDL/jogos usarem Wayland
env = CLUTTER_BACKEND,wayland  # GNOME apps
env = GDK_SCALE,1


#env = GTK_THEME,Adwaita:dark
env = XCURSOR_THEME,MacTahoe-dark
env = XCURSOR_SIZE,24

# Ozone
env = OZONE_PLATFORM,wayland
env = ELECTRON_OZONE_PLATFORM_HINT,wayland

# XWayland
xwayland {
  force_zero_scaling = true
}

# Polkit and authentication
# Using polkit-kde-authentication-agent-1
env = SSH_ASKPASS_REQUIRE,never
