env = QT_QPA_PLATFORM,wayland
env = ELECTRON_OZONE_PLATFORM_HINT,auto
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_QPA_PLATFORMTHEME_QT6,qt6ct
env = TERMINAL,kitty

# === Environment Variables ===
env = XDG_DATA_DIRS,$XDG_DATA_DIRS:/var/lib/flatpak/exports/share:~/.local/share/flatpak/exports/share
env = PATH,$PATH:~/.local/bin

# === Extras úteis (opcional) ===
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
env = GDK_BACKEND,wayland,x11  # GTK apps usarem Wayland primeiro
env = SDL_VIDEODRIVER,wayland  # SDL/jogos usarem Wayland
env = CLUTTER_BACKEND,wayland  # GNOME apps

#env = GTK_THEME,Adwaita:dark
env = XCURSOR_THEME,NomeDoCursor
env = XCURSOR_SIZE,24
